version: "3"

services:
  baileys-api:
    image: "ghcr.io/fazer-ai/baileys-api:latest"
    pull_policy: always
    volumes:
      - "storage:/app/storage"
    environment:
      - NODE_ENV=production
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - BAILEYS_LOG_LEVEL=${BAILEYS_LOG_LEVEL:-error}
      - BAILEYS_PROVIDER_DEFAULT_API_KEY=${BAILEYS_PROVIDER_DEFAULT_API_KEY}
    command:
      - sh
      - "-c"
      - "bun manage-api-keys create user ${BAILEYS_PROVIDER_DEFAULT_API_KEY} && bun start"
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - "wget -qO- http://localhost:3025/status"
      interval: 20s
      timeout: 20s
      retries: 10
